FROM golang:1.14-alpine

RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /app/child

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

CMD CGO_ENABLED=0 go test
