name: Test Integration
on:
  pull_request:
    branches:
      - main
jobs:
  mothership_test:
    name: Run mothership test
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Test
        run: docker-compose -f docker-compose-m.test.yml up  --exit-code-from mothership

  child_test:
    name: Run child test
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.14.x'

      - name: Test
        run: docker-compose -f docker-compose-c.test.yml up  --exit-code-from child
